# Workflow
# Should have name 
name: Hello
# on tells when the workflow runs
on: 
  workflow_dispatch:
# Jobs
# Should be inside the Workflow
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"
# Steps
# Should be inside the Job

# Actions
# Should be inside steps
