name: Job Output Example

on:
  workflow_dispatch:

jobs:
  get-date:
    runs-on: self-hosted

    outputs:
      date: ${{ steps.set-date.outputs.date }}

    steps:
      - name: Set output
        id: set-date
        run: |
          echo "date=$(date)" >> "$GITHUB_OUTPUT"

  print-date:
    runs-on: self-hosted
    needs: get-date

    steps:
      - name: Print date
        run: |
          echo "Date: ${{ needs.get-date.outputs.date }}"