## What is the goal of your workflow
# Goal: Whenever someone changes the python code, 
# the linter will check if the sytax, format, indentation (Linting) is correct or not
name: Auto-Linter
on:
  push:
    paths: "*.py"
jobs:
  code-linting:
  runs-on: ubuntu-latest
  steps:
    # Cloningg the code
    - name: Clone the code 
      uses: actions/checkout@v7
    #Installing linter
    - name: Install the application package 
      run: pip install ruff
    #Checking for syntax error
    - name: Check the files for linting 
      run: ruff check .
