name: manual-trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "staging"
        type: choice
        matrix:
          option: [staging, production]

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Running workflow for environment: ${{ matrix.option }}"
