name: manual-trigger
on:
  workflow_dispatch:
    inputs:
      environments:
        description: "Choose an environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
jobs: 
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: print environment
        run: echo "Running workflow for environment : ${{ github.event.inputs.environment }}"
