name: matrixbuild
on:
  workflow_dispatch:
jobs:
  python-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.14, 3.11, 3.12]
        os: [ubuntu-latest, ubuntu-slim, windows-latest]
        exclude:
          - python-version: 3.11
            os: windows-latest
    steps:
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print python version
        run: python --version

      - name: forced failure on Python
        if: matrix.python-version == '3.11'
        run: exit 1
          
