name: pr-checking
on:
  pull_request:
    branches: main
jobs:
  PR-checking:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "PR checking for branch :${{ github.head_ref }}

