name: pr-checking
on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  PR-checking:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "PR checking for branch :${{ github.head_ref }}"

