name: Secrets
on:
  workflow_dispatch:
jobs:
  Read-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exists
        run: |
          if [ -z "${{ secrets.MY_SECRET }}" ]; then
          echo " The secret is set: false."
          else
          echo " The secret is set: true."
          fi
      - name: Read secret from repository
        run: echo "The secret is ${{ secrets.MY_SECRET }}"